  
version: "3"

services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    command: >
      sh -c "python3 manage.py wait_for_db &&
      python3 manage.py makemigrations &&
      python3 manage.py migrate monitoring &&
      python3 manage.py migrate control &&
      python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    hostname: db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
