# Generated by Django 3.2 on 2021-04-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='state',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=0),
        ),
    ]
