# Generated by Django 3.2 on 2021-04-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='humiditysample',
            name='plant_id',
            field=models.IntegerField(default=0),
        ),
    ]
